### ISSUE TITLE
MoltenVK/mvk_vulkan.h' file not found

### ISSUE THREAD

**Issue by zn123** [obsproject/obs-deps#61] opened 2021-06-25 09:46 UTC
### Operating System Info

macOS 11.3

### Other OS

mac

### OBS Studio Version

27.0.1

### OBS Studio Log URL

ror: 'MoltenVK/mvk_vulkan.h' file not found

### Expected Behavior

./build-script-macos-02.sh 

### Current Behavior

/Users/wangxueyan/zntemp/temp_qt/_obs/obs-deps/CI_BUILD/qt-everywhere-src-5.15.2/qtbase/src/plugins/platforms/cocoa/qcocoawindow.h:56:10: fatal error: 'MoltenVK/mvk_vulkan.h' file not found
#include <MoltenVK/mvk_vulkan.h>

### Steps to Reproduce

1.
2.
3.
...

**Comment by PatTheMav** [comment] 2021-06-25 10:48
Please fill out the issue template properly - it's there for a reason. Without steps to reproduce or other environmental information (e.g. custom packages installed) we have no way to check what the root cause of the issue could be and thus are unable to fix it.

**Comment by RytoEX** [comment] 2021-11-08 01:14
I'm closing this issue because the reporter never replied to request for more information.

**Closed by RytoEX** 2021-11-08 01:14 UTC
